### ISSUE TITLE
Deler av ¶ tegn i h2 henger igjen i Chrome

### ISSUE THREAD

**Issue by stiancor** [kodemaker/kodemaker.no#72]
Dersom man går inn på f.eks http://www.kodemaker.no/stian/ eller hvilken som helst annen personside og flytter muspekeren over en h2 så vises dette tegnet: ¶ 

Ser at det er en <span class="anchor-marker">¶</span> og at denne har style display: none, men i f.eks chrome så blir noen hvite piksler værende igjen når man flytter muspekeren bort. Det skjer ikke i f.eks firefox.

Dette er likt som på github ser jeg (etter å ha snakket med Magnar), men der er forskjellen at det bare er span-taggen som ligger inne i a-taggen som igjen ligger inne i h2. Altså ikke selve overskriften. I tillegg ligger det ikke noe tegn i selve htmlen som hos oss (¶). Det ser ut til å være styrt i CSSen

**Comment by cjohansen** [comment]
Der kan du se - noen ganger forsvinner problemer av seg selv om man bare venter litt.
