### ISSUE TITLE
Lange personnavn i referanser.

### ISSUE THREAD

**Issue by kolbjorn** [kodemaker/kodemaker.no#77]
I seksjonen for deltakere i et prosjekt blir det litt mindre fint når vi tar med 'lange navn' på deltakere.

Kunne vi ha laget denne biten på en måte som bare tok med fornavnet?

![nsb_rask___kodemaker](https://cloud.githubusercontent.com/assets/559117/6663227/bba0aa32-cbc4-11e4-96bf-0b6449e498ac.png)

Eks.som fungerer, men...
http://www.kodemaker.no/referanser/spid-techdocs/#kodemakere-hos-schibsted

**Comment by magnars** [comment]
Jau, det er jo noen seriøst lange navn i dette selskapet også. ;-)

Det er bare å endre til `:first-name` her: https://github.com/kodemaker/kodemaker.no/blob/master/src/kodemaker_no/pages/reference_pages.clj#L14

**Comment by kolbjorn** [comment]
OK.  Da skriver jeg Clojure på CV-en min.

**Comment by magnars** [comment]
Konge!

**Comment by kolbjorn** [comment]
![nsb_rask___kodemaker](https://cloud.githubusercontent.com/assets/559117/6663717/9c92d548-cbc9-11e4-83c2-1a2e7fe2baeb.png)
