### ISSUE TITLE
:team-size trenger grafikk for team med flere enn 6 deltagere

### ISSUE THREAD

**Issue by steintore** [kodemaker/kodemaker.no#79]
I NSB RASK-prosjektet har vi tilsammen 7 involverte kodemakere, men ingen grafikk for visning av dette.

:team-size over f.eks 6 kunne vært en og samme illustrasjon/grafikk

**Comment by magnars** [comment]
Enig. Ber du Kolbjørn gi et lite oppdrag til Elisabeth for å finne en løsning? :)

**Comment by cjohansen** [comment]
Finner ingen `:team-size` på mer enn 3 i kodebasen nå. Er dette fortsatt et issue?
