### ISSUE TITLE
Bare ren tekst...

### ISSUE THREAD

**Issue by kolbjorn** [kodemaker/kodemaker.no#80]
Dette kan sikkert alle hjelpe meg med (og evt. lage)  ;)

Vi forsøke å skrive tekst som starter på linje med referanseboksene vertikalt.

How-to...?

---

:type xxx?
:body

Fint tekste her ja?

**Comment by magnars** [comment]
`xxx` = `illustrated-column` vil jeg tro, uten illustrasjon.

**Comment by cjohansen** [comment]
Er dette fortsatt aktuelt?
