### ISSUE TITLE
Blog link/icon på personside ?

### ISSUE THREAD

**Issue by rundis** [kodemaker/kodemaker.no#81]
Det begynner jo å bli endel av oss som har personlige blogger. Kanskje det burde vært mulig å legge til en link til sin personlige blog (på like linje med twitter, coderwall, lnkedin osv). Kan godt slenge inn en pull request dersom ønskelig, men trenger vel rappt et passende icon i såfall.

**Comment by magnars** [comment]
Er kanskje mulig å sjekke med Elisabeth om å lage et ikon. Eller vi kan prøve å lage et selv. En blyant f.x.?
